#!/usr/bin/env python3
"""The cycle search in the limit: is the midrange comparison on Sato--Tate
measures transitive?

Brief F's reduction: two families of curves whose normalised traces have
limiting distributions ``mu`` and ``nu`` satisfy

    f < g   iff   mid_tau (Psi_mu - Psi_nu) < 0,      Psi = K/tau,

with the two endpoints forced, ``Psi(0) = 0`` and ``Psi(inf) = alpha_max``.  So
cycles persist as ``q -> inf`` iff that comparison is non-transitive.

**Three exact structural facts organise the search.**

*(i) ``alpha_max`` is the genus.*  For any compact subgroup ``G`` of ``USp(2g)``
of positive dimension the trace is continuous and equals ``2g`` at the identity,
so ``ess sup = 2g`` for every family with infinite monodromy, whatever ``G``.
Fixing ``alpha_max`` therefore means fixing the genus.

*(ii) the reachable set is the convex hull of a lattice cone.*  Products of
independent factors add ``K``, hence add ``Psi``; ``k`` isogenous copies of a
factor dilate ``tau`` by ``k``; and disconnected monodromy realises convex
combinations, whose MGFs mix.  So the reachable set is generated by the finite
list of product measures enumerated here.

*(iii) two derived coordinates decide crossings.*  With ``v = E[alpha^2] = m_2``
and ``t`` the edge exponent,

    Psi_mu(tau) = v tau/2 + O(tau^2)                       (tau -> 0)
    Psi_mu(tau) = alpha_max - (t log tau - log A)/tau       (tau -> inf)

so at fixed ``alpha_max`` the small-``tau`` order is by ``v`` and the
large-``tau`` order by ``-t``.  ``Psi_mu - Psi_nu`` crosses whenever ``v`` and
``t`` are ordered the same way -- the trade the cycles session identified from
the finite-``q`` side ("a signature whose Psi rises faster at small tau must
flatten before the common endpoint").  Both are additive over products, so the
crossing structure of the whole cone is a two-dimensional combinatorial fact.

Across ``alpha_max`` classes the endpoint ``D(inf) = alpha_max(a)-alpha_max(b)``
is nonzero, and the seed run for this brief asserted that it always dominates,
making the cross-genus comparison a total order.  **That is false**, and the
cycles found here are exactly the cross-genus ones: a large-variance measure of
smaller ``alpha_max`` can overtake a small-variance measure of larger
``alpha_max`` in the midrange, because the interior excursion is ``Theta(1)``
and so is the endpoint gap.

    python research/sato_tate_limit/cone_search.py
"""

from __future__ import annotations

import csv
import itertools
import json
import math
from pathlib import Path

import numpy as np

import st_lib as S

HERE = Path(__file__).resolve().parent

TAU = S.tau_grid(1e-4, 1e5, 3001)
LOGTAU = np.log(TAU)

# realisability tiers, see FINDINGS "Realisability"
TIER = {
    "SU2": 0,       # non-CM elliptic pencil / big monodromy: realised, witnesses given
    "USp2": 0, "USp4": 0, "USp6": 0, "USp8": 0, "USp10": 0,
    "U1": 1,        # torus monodromy: not realised vertically, see FINDINGS
    "SO3": 2, "SO4": 2, "SO5": 2, "SO6": 2, "SO7": 2,   # orthogonal: not H^1 of a curve
}
TIER_NAME = {0: "symplectic (realised)", 1: "torus (conditional)",
             2: "orthogonal (not curves)"}


def factor_tier(f: S.Factor) -> int:
    base = TIER[f.group]
    if f.group == "U1" and f.atom > 0:
        return 1
    return base


# ------------------------------------------------------------------- library


def factor_list(alpha_cap: float, max_mult: int = 4) -> list[S.Factor]:
    out: list[S.Factor] = []
    for k in range(1, max_mult + 1):
        out.append(S.Factor("SU2", k, 0.0))
        out.append(S.Factor("U1", k, 0.0))
        out.append(S.Factor("U1", k, 0.5))          # the CM measure
    for g in (2, 3, 4, 5):
        for k in (1, 2):
            out.append(S.Factor(f"USp{2 * g}", k, 0.0))
    for n in (3, 4, 5, 6, 7):
        out.append(S.Factor(f"SO{n}", 1, 0.0))
    return [f for f in out if f.alpha_max <= alpha_cap + 1e-9]


def enumerate_products(alpha_cap: float, factors: list[S.Factor]) -> list[S.Measure]:
    """Every multiset of factors with total ``alpha_max <= alpha_cap``."""

    factors = sorted(factors, key=lambda f: (f.alpha_max, f.group, f.multiplicity,
                                             f.atom))
    out: list[S.Measure] = []

    def rec(start: int, used: float, chosen: list[S.Factor]) -> None:
        if chosen:
            out.append(S.Measure(tuple(chosen)))
        for i in range(start, len(factors)):
            f = factors[i]
            if used + f.alpha_max <= alpha_cap + 1e-9:
                rec(i, used + f.alpha_max, chosen + [f])

    rec(0, 0.0, [])
    seen: dict[str, S.Measure] = {}
    for m in out:
        seen.setdefault(m.label, m)
    return list(seen.values())


# ------------------------------------------------------------------ analysis


def psi_table(lib: list[S.Measure]) -> np.ndarray:
    return np.array([m.Psi(TAU) for m in lib])


def mid_matrix(psis: np.ndarray, amax: np.ndarray) -> tuple[np.ndarray, np.ndarray,
                                                            np.ndarray]:
    n = psis.shape[0]
    mid = np.zeros((n, n))
    hi_all = np.zeros((n, n))
    lo_all = np.zeros((n, n))
    for i in range(n):
        d = psis[i][None, :] - psis
        end = amax[i] - amax
        hi = np.maximum(np.maximum(d.max(axis=1), 0.0), end)
        lo = np.minimum(np.minimum(d.min(axis=1), 0.0), end)
        mid[i] = 0.5 * (hi + lo)
        hi_all[i] = hi
        lo_all[i] = lo
    np.fill_diagonal(mid, 0.0)
    return mid, hi_all, lo_all


def refined_mid(a: S.Measure, b: S.Measure, psi_a: np.ndarray,
                psi_b: np.ndarray) -> float:
    """``mid`` with the two extrema located exactly, not read off the grid.

    The grid gives ``argmax``/``argmin`` to within one step; a golden-section
    search on ``log tau`` inside the bracketing pair of steps then evaluates
    ``Psi`` directly, so the reported extremum is exact to ``1e-12`` rather than
    to the ``O((dlog tau)^2)`` of a grid read-off.
    """

    d = psi_a - psi_b

    def value(s: float) -> float:
        t = np.array([math.exp(s)])
        return float((a.K(t) - b.K(t))[0] / t[0])

    def polish(i: int, sign: float) -> float:
        lo = LOGTAU[max(i - 1, 0)]
        hi = LOGTAU[min(i + 1, LOGTAU.size - 1)]
        phi = (math.sqrt(5.0) - 1.0) / 2.0
        x1, x2 = hi - phi * (hi - lo), lo + phi * (hi - lo)
        f1, f2 = sign * value(x1), sign * value(x2)
        for _ in range(60):
            if f1 > f2:
                hi, x2, f2 = x2, x1, f1
                x1 = hi - phi * (hi - lo)
                f1 = sign * value(x1)
            else:
                lo, x1, f1 = x1, x2, f2
                x2 = lo + phi * (hi - lo)
                f2 = sign * value(x2)
            if hi - lo < 1e-13:
                break
        return sign * max(f1, f2)

    hi_val = max(polish(int(np.argmax(d)), +1.0), 0.0,
                 a.alpha_max - b.alpha_max)
    lo_val = min(polish(int(np.argmin(d)), -1.0), 0.0,
                 a.alpha_max - b.alpha_max)
    return 0.5 * (hi_val + lo_val)


def find_cycles(mid: np.ndarray, keep: np.ndarray, tol: float) -> list[tuple]:
    idx = np.where(keep)[0]
    out = []
    for i, j, k in itertools.combinations(idx, 3):
        for a, b, c in ((i, j, k), (i, k, j)):
            if mid[a, b] < -tol and mid[b, c] < -tol and mid[c, a] < -tol:
                out.append((a, b, c, min(-mid[a, b], -mid[b, c], -mid[c, a])))
    return sorted(out, key=lambda r: -r[3])


def transitivity_report(mid: np.ndarray, keep: np.ndarray, tol: float) -> dict:
    idx = np.where(keep)[0]
    n = len(idx)
    sub = mid[np.ix_(idx, idx)]
    strict = sub < -tol
    triangles = math.comb(n, 3) * 2
    cyc = 0
    for i, j, k in itertools.combinations(range(n), 3):
        for a, b, c in ((i, j, k), (i, k, j)):
            if strict[a, b] and strict[b, c] and strict[c, a]:
                cyc += 1
    return {"members": n, "oriented_triangles": triangles, "cycles": cyc}


def curl_residual(mid: np.ndarray) -> tuple[float, np.ndarray]:
    psi = -mid.mean(axis=1)
    grad = psi[None, :] - psi[:, None]
    return float(np.linalg.norm(mid - grad) / np.linalg.norm(mid)), psi


# --------------------------------------------------------------------- main


def main() -> int:
    cap = 8.0
    lib = enumerate_products(cap, factor_list(cap))
    lib.sort(key=lambda m: (m.alpha_max, m.variance, m.tail, m.label))
    tiers = np.array([max(factor_tier(f) for f in m.factors) for m in lib])
    amax = np.array([m.alpha_max for m in lib])
    var = np.array([m.variance for m in lib])
    tail = np.array([m.tail for m in lib])
    print(f"library: {len(lib)} product measures with alpha_max <= {cap:g}")
    for t in (0, 1, 2):
        print(f"   tier {t} ({TIER_NAME[t]}): {int((tiers == t).sum())}")
    psis = psi_table(lib)

    # the far tail must be monotone, or the grid would be truncating an extremum
    tail_slope = np.abs(psis[:, -1] - amax) - np.abs(psis[:, -2] - amax)
    print(f"\n  far-tail check: |Psi - alpha_max| decreasing at tau = 1e5 for "
          f"{int((tail_slope < 0).sum())}/{len(lib)} measures")

    mid, hi, lo = mid_matrix(psis, amax)
    tol = 1e-6

    print()
    print("=" * 78)
    print("transitivity by realisability tier and by alpha_max class")
    print("=" * 78)
    rows = []
    tiersets = {
        "symplectic only": tiers == 0,
        "symplectic + torus": tiers <= 1,
        "everything (incl. orthogonal)": tiers <= 2,
    }
    for name, keep in tiersets.items():
        rep = transitivity_report(mid, keep, tol)
        print(f"  {name:<32} members {rep['members']:>4}   "
              f"oriented triangles {rep['oriented_triangles']:>9}   "
              f"3-cycles {rep['cycles']:>6}")
        rows.append(["tier", name, rep["members"], rep["oriented_triangles"],
                     rep["cycles"], ""])
        for a in (4.0, 6.0, 8.0):
            k2 = keep & (np.abs(amax - a) < 1e-9)
            r2 = transitivity_report(mid, k2, tol)
            print(f"     restricted to alpha_max = {a:g}: members {r2['members']:>3}"
                  f"   triangles {r2['oriented_triangles']:>7}"
                  f"   3-cycles {r2['cycles']:>5}")
            rows.append(["tier-class", f"{name} @ alpha_max={a:g}", r2["members"],
                         r2["oriented_triangles"], r2["cycles"], ""])
        print()

    print("=" * 78)
    print("the cycles")
    print("=" * 78)
    cyc_rows = []
    for name, keep in tiersets.items():
        found = find_cycles(mid, keep, tol)
        print(f"\n  {name}: {len(found)} oriented 3-cycles")
        shown = 0
        seen_sets = set()
        for a, b, c, margin in found:
            key = frozenset((a, b, c))
            if key in seen_sets:
                continue
            seen_sets.add(key)
            shown += 1
            if shown > 6:
                continue
            ref = [refined_mid(lib[x], lib[y], psis[x], psis[y])
                   for x, y in ((a, b), (b, c), (c, a))]
            print(f"    {lib[a].label} < {lib[b].label} < {lib[c].label} < ...")
            for (x, y), r in zip(((a, b), (b, c), (c, a)), ref):
                print(f"       mid({lib[x].label:>22} -> {lib[y].label:<22}) = "
                      f"{mid[x, y]:+.9f}   (fine grid {r:+.9f})")
            print(f"       alpha_max {amax[a]:g},{amax[b]:g},{amax[c]:g}   "
                  f"m2 {var[a]:g},{var[b]:g},{var[c]:g}   "
                  f"t {tail[a]:g},{tail[b]:g},{tail[c]:g}   "
                  f"margin {margin:.4e}  (fine {min(-r for r in ref):.4e})")
            cyc_rows.append([name, lib[a].label, lib[b].label, lib[c].label,
                             f"{amax[a]:g}/{amax[b]:g}/{amax[c]:g}",
                             f"{var[a]:g}/{var[b]:g}/{var[c]:g}",
                             f"{tail[a]:g}/{tail[b]:g}/{tail[c]:g}",
                             f"{margin:.6e}", f"{min(-r for r in ref):.6e}"])
        print(f"    ({len(seen_sets)} distinct triples)")
        rows.append(["cycles", name, len(found), len(seen_sets), "", ""])

    # ------------------------------------------------ the seed's genus-2 table
    print()
    print("=" * 78)
    print("the seed's ten genus-two measures, recomputed")
    print("=" * 78)
    seed_labels = ["USp4", "SU2 x SU2", "U1 x U1", "SU2 x U1", "CM x CM",
                   "SU2 x CM", "U1 x CM", "2.SU2", "2.U1", "2.CM"]
    index = {m.label: i for i, m in enumerate(lib)}
    sel = [index[s] for s in seed_labels]
    sub = mid[np.ix_(sel, sel)]
    order = sorted(range(len(sel)), key=lambda i: -(-sub[i].mean()))
    curl, _ = curl_residual(sub)
    rep = transitivity_report(mid, np.isin(np.arange(len(lib)), sel), tol)
    print(f"  3-cycles: {rep['cycles']} of {rep['oriented_triangles']} "
          f"oriented triangles")
    print(f"  curl residual ||mid - grad psi|| / ||mid|| = {curl:.6e}   "
          f"(seed reported 6.8e-2)")
    ncross = 0
    for i, j in itertools.combinations(range(len(sel)), 2):
        d = psis[sel[i]] - psis[sel[j]]
        scale = max(np.abs(d).max(), 1e-300)
        if S.sign_changes(d, tol=1e-9 * scale) >= 1:
            ncross += 1
    print(f"  crossing pairs: {ncross} of 45   (seed reported 3 of 45)")
    linear = [seed_labels[i] for i in order]
    print("  total order (least first): " + " < ".join(linear))
    rows.append(["seed-table", "cycles", rep["cycles"], rep["oriented_triangles"],
                 f"{curl:.6e}", ncross])

    # --------------------------------------------- (v, t) crossing criterion
    print()
    print("=" * 78)
    print("the (m2, t) crossing criterion, tested on every same-alpha_max pair")
    print("=" * 78)
    agree = total = 0
    disagree = []
    for a in (2.0, 4.0, 6.0, 8.0):
        sel2 = np.where(np.abs(amax - a) < 1e-9)[0]
        for i, j in itertools.combinations(sel2, 2):
            d = psis[i] - psis[j]
            scale = max(np.abs(d).max(), 1e-300)
            crossed = S.sign_changes(d, tol=1e-9 * scale) >= 1
            pred = (var[i] - var[j]) * (tail[i] - tail[j]) > 0
            total += 1
            if crossed == pred:
                agree += 1
            else:
                disagree.append((lib[i].label, lib[j].label, crossed, pred))
    print(f"  agrees on {agree} of {total} same-alpha_max pairs "
          f"({100 * agree / total:.2f}%)")
    print("  disagreements -- every one is an exact tie in m2, where the product")
    print("  criterion is vacuous and the crossing is decided at higher order:")
    for x, y, cr, pr in disagree[:12]:
        print(f"    {x:<26} vs {y:<26} crossed={cr} predicted={pr}")
    rows.append(["crossing-criterion", "", agree, total, "", ""])

    # ------------------------------------- matched (alpha_max, m2), differing m3/m4
    print()
    print("=" * 78)
    print("pairs matched in alpha_max AND m2 -- decided by higher cumulants only")
    print("=" * 78)
    print("  (the configuration of the certified q = 101 cycle, where two of the")
    print("   three pencils share max fibre, m2 and nu(P))")
    print(f"\n  {'pair':<52}{'t':>12}{'mid':>14}{'sign changes':>13}")
    matched = 0
    for a in (4.0, 6.0, 8.0):
        sel2 = np.where(np.abs(amax - a) < 1e-9)[0]
        for i, j in itertools.combinations(sel2, 2):
            if abs(var[i] - var[j]) > 1e-9:
                continue
            matched += 1
            if matched <= 14:
                d = psis[i] - psis[j]
                sc = S.sign_changes(d, tol=1e-9 * max(np.abs(d).max(), 1e-300))
                print(f"  {lib[i].label + ' | ' + lib[j].label:<52}"
                      f"{tail[i]:>6.1f}/{tail[j]:<5.1f}{mid[i, j]:>14.7f}{sc:>13}")
    follows = ties = crossing = 0
    for a in (4.0, 6.0, 8.0):
        for i, j in itertools.combinations(np.where(np.abs(amax - a) < 1e-9)[0], 2):
            if abs(var[i] - var[j]) > 1e-9:
                continue
            if S.sign_changes(psis[i] - psis[j]) >= 1:
                crossing += 1
            if abs(tail[i] - tail[j]) < 1e-9:
                ties += 1
            elif (tail[i] > tail[j]) == (mid[i, j] < 0):
                follows += 1
    print(f"\n  {matched} such pairs in the library; {ties} of them also tie in t,")
    print(f"  and of the remaining {matched - ties}, {follows} follow the edge")
    print(f"  exponent -- larger t precedes.  {crossing} of the {matched} cross.")
    rows.append(["matched-m2-detail", matched, ties, follows, crossing, ""])
    rows.append(["matched-m2", "", matched, "", "", ""])

    with (HERE / "cone_summary.csv").open("w", newline="", encoding="utf-8") as fh:
        wr = csv.writer(fh)
        wr.writerow(["kind", "label", "a", "b", "c", "d"])
        wr.writerows(rows)
    with (HERE / "cycles.csv").open("w", newline="", encoding="utf-8") as fh:
        wr = csv.writer(fh)
        wr.writerow(["tier", "measure_1", "measure_2", "measure_3", "alpha_max",
                     "m2", "edge_exponent", "margin_coarse", "margin_fine"])
        wr.writerows(cyc_rows)
    with (HERE / "library.csv").open("w", newline="", encoding="utf-8") as fh:
        wr = csv.writer(fh)
        wr.writerow(["measure", "alpha_max", "m2", "edge_exponent_t", "tier"])
        for i, m in enumerate(lib):
            wr.writerow([m.label, f"{m.alpha_max:g}", f"{m.variance:.6f}",
                         f"{m.tail:.4f}", TIER_NAME[int(tiers[i])]])
    with (HERE / "cone_result.json").open("w", encoding="utf-8") as fh:
        json.dump({"n_measures": len(lib), "tau_grid": [float(TAU[0]),
                                                        float(TAU[-1]),
                                                        int(TAU.size)],
                   "tolerance": tol}, fh, indent=2)
    print("\nwritten: cone_summary.csv, cycles.csv, library.csv")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
