#!/usr/bin/env python3
"""``N_k(g -> f)`` for binary quadratic ``g, f : F_q^2 -> F_q``, any odd prime ``q``.

This is the general-``q`` companion to ``affine_atoms.py``, which is hard-wired
to ``q = 3`` and works with value tables on ``F_3^{2k}``.  Here we use the
*jet representation*, which is exact for every odd ``q`` and much smaller.

Reduction lemma (``FINDINGS.md``, restated).  For ``f, g : F_q^2 -> F_q``,

    f^{x k}  <=_aff  g^{x r}
      <=>  there are affine  alpha_1, ..., alpha_r : F_q^{2k} -> F_q^2  with
           f(x_i)  in  span{ g o alpha_1, ..., g o alpha_r } + F_q . 1
           for every  i = 1, ..., k ,

because an affine  a : F_q^{2k} -> F_q^{2r}  is exactly a list of ``r`` affine
maps into ``F_q^2`` and an affine  b : F_q^r -> F_q^k  is exactly ``k`` affine
functionals of the ``r`` outputs.

Jet representation.  For ``q >= 3`` a polynomial of total degree at most two in
``n`` variables has all individual exponents ``< q``, so it is determined by its
coefficients as a function on ``F_q^n``.  Write

    J(h) = (quadratic part of h, linear part of h)  in  Sym^2 (+) V^*

and drop the constant term.  Then ``h in span{h_j} + F_q . 1`` is *equivalent*
to ``J(h) in span{J(h_j)}``: the constants are exactly the kernel of ``J``.  So

    N_k(g -> f) = min { r : J(f(x_1)), ..., J(f(x_k))  all lie in the span of
                        r  vectors  J(g o alpha) } .

With ``g(u,v) = a u^2 + b uv + c v^2 + d u + e v`` and
``alpha(x) = (l(x) + s, m(x) + t)``,

    J(g o alpha) = ( a l^2 + b l m + c m^2 ,
                     (2 a s + b t + d) l + (b s + 2 c t + e) m ) ,

so the atom set is generated by looping over ``(l, m, s, t)``.
"""

from __future__ import annotations

from dataclasses import dataclass
from itertools import product

import numpy as np


# ---------------------------------------------------------------------------
# binary quadratics, as coefficient tuples (a, b, c, d, e) of a u^2+b uv+c v^2
#                                                            + d u + e v
# ---------------------------------------------------------------------------

BINARY = {
    "linear":      (0, 0, 0, 1, 0),   # x
    "rank1":       (1, 0, 0, 0, 0),   # x^2
    "split":       (0, 1, 0, 0, 0),   # x y
    "sum2":        (1, 0, 1, 0, 0),   # x^2 + y^2
    "parabolic":   (1, 0, 0, 0, 1),   # x^2 + y
}


def norm_form(q: int) -> tuple[int, int, int, int, int]:
    """``x^2 - n y^2`` with ``n`` the least non-residue: anisotropic for all odd q."""

    n = least_non_residue(q)
    return (1, 0, (-n) % q, 0, 0)


def least_non_residue(q: int) -> int:
    squares = {(t * t) % q for t in range(1, q)}
    for n in range(2, q):
        if n not in squares:
            return n
    raise ValueError(f"no non-residue mod {q}")


def is_anisotropic(coefficients, q: int) -> bool:
    """Does the quadratic part vanish only at the origin of ``F_q^2``?"""

    a, b, c = coefficients[:3]
    for u in range(q):
        for v in range(q):
            if (u, v) == (0, 0):
                continue
            if (a * u * u + b * u * v + c * v * v) % q == 0:
                return False
    return True


# ---------------------------------------------------------------------------
# jets
# ---------------------------------------------------------------------------

def monomial_index(n: int):
    """Index of the quadratic monomials ``x_i x_j``, ``i <= j``."""

    pairs = [(i, j) for i in range(n) for j in range(i, n)]
    return pairs, {p: t for t, p in enumerate(pairs)}


@dataclass(frozen=True)
class JetSpace:
    q: int
    n: int
    pairs: tuple
    dim: int

    @staticmethod
    def make(q: int, n: int) -> "JetSpace":
        pairs, _ = monomial_index(n)
        return JetSpace(q=q, n=n, pairs=tuple(pairs), dim=len(pairs) + n)

    def powers(self) -> np.ndarray:
        return (self.q ** np.arange(self.dim)).astype(np.int64)

    def encode(self, rows: np.ndarray) -> np.ndarray:
        return (np.atleast_2d(rows).astype(np.int64) @ self.powers())

    def decode(self, codes) -> np.ndarray:
        codes = np.atleast_1d(np.asarray(codes, dtype=np.int64))
        out = (codes[:, None] // self.powers()[None, :]) % self.q
        return out.astype(np.int8)


def jet_of_form(space: JetSpace, quad: np.ndarray, lin: np.ndarray) -> np.ndarray:
    """Pack a symmetric matrix ``quad`` (as a full matrix) and ``lin`` into a jet.

    The quadratic form is ``sum_{i<=j} coeff_{ij} x_i x_j`` with
    ``coeff_{ii} = quad[i,i]`` and ``coeff_{ij} = 2 quad[i,j]`` for ``i < j``.
    """

    q, n = space.q, space.n
    row = np.zeros(space.dim, dtype=np.int8)
    for t, (i, j) in enumerate(space.pairs):
        row[t] = (quad[i, j] if i == j else 2 * quad[i, j]) % q
    row[len(space.pairs):] = np.asarray(lin) % q
    return row


# ---------------------------------------------------------------------------
# atom generation
# ---------------------------------------------------------------------------

def atom_codes(space: JetSpace, g, chunk: int = 1 << 16) -> np.ndarray:
    """Sorted distinct codes of the jets ``J(g o alpha)``, ``alpha`` affine.

    Exhaustive: every ``(l, m, s, t)`` with ``l, m in (F_q^n)^*`` and
    ``s, t in F_q`` is enumerated.
    """

    q, n = space.q, space.n
    a, b, c, d, e = (x % q for x in g)
    vectors = np.array(list(product(range(q), repeat=n)), dtype=np.int16)
    size = vectors.shape[0]
    npairs = len(space.pairs)
    ii = np.array([i for i, _ in space.pairs])
    jj = np.array([j for _, j in space.pairs])
    diagonal = ii == jj

    codes: list[np.ndarray] = []
    powers = space.powers()
    for start in range(0, size, chunk):
        block = vectors[start:start + chunk]                    # (B, n)
        for m in vectors:                                       # (n,)
            ll_i, ll_j = block[:, ii], block[:, jj]
            mm_i, mm_j = m[ii][None, :], m[jj][None, :]
            # off-diagonal entries carry the factor 2 from x_i x_j
            quad = np.where(diagonal[None, :],
                            (a * ll_i * ll_i + b * ll_i * mm_i
                             + c * mm_i * mm_i),
                            (2 * a * ll_i * ll_j
                             + b * (ll_i * mm_j + ll_j * mm_i)
                             + 2 * c * mm_i * mm_j)) % q
            for s in range(q):
                for t in range(q):
                    alpha = (2 * a * s + b * t + d) % q
                    beta = (b * s + 2 * c * t + e) % q
                    lin = (alpha * block + beta * m[None, :]) % q
                    row = np.concatenate([quad, lin], axis=1).astype(np.int64)
                    codes.append(row @ powers)
        # keep memory bounded
        codes = [np.unique(np.concatenate(codes))]
    return np.unique(np.concatenate(codes))


# ---------------------------------------------------------------------------
# targets
# ---------------------------------------------------------------------------

def target_jets(space: JetSpace, f, k: int) -> np.ndarray:
    """Jets of ``f(x_i)``, ``i = 1..k``, on ``F_q^{2k}`` (``n = 2k``)."""

    q = space.q
    a, b, c, d, e = (x % q for x in f)
    rows = []
    for i in range(k):
        quad = np.zeros((space.n, space.n), dtype=np.int64)
        u, v = 2 * i, 2 * i + 1
        quad[u, u] = a
        quad[u, v] = quad[v, u] = b * pow(2, q - 2, q)   # b/2
        quad[v, v] = c
        lin = np.zeros(space.n, dtype=np.int64)
        lin[u], lin[v] = d, e
        rows.append(jet_of_form(space, quad % q, lin))
    return np.array(rows, dtype=np.int8)


# ---------------------------------------------------------------------------
# linear algebra over F_q
# ---------------------------------------------------------------------------

class Subspace:
    """Row space over F_q in reduced row echelon form."""

    __slots__ = ("q", "rows", "pivots", "width")

    def __init__(self, q: int, width: int):
        self.q = q
        self.width = width
        self.rows = np.zeros((0, width), dtype=np.int64)
        self.pivots: list[int] = []

    @property
    def dimension(self) -> int:
        return len(self.pivots)

    def reduce(self, matrix) -> np.ndarray:
        result = np.array(matrix, dtype=np.int64, copy=True) % self.q
        if result.ndim == 1:
            result = result.reshape(1, -1)
        for row, column in zip(self.rows, self.pivots):
            coefficient = result[:, column].copy()
            nonzero = coefficient != 0
            if nonzero.any():
                result[nonzero] = (result[nonzero]
                                   - coefficient[nonzero, None] * row[None, :]) % self.q
        return result

    def contains(self, vector) -> bool:
        return not self.reduce(vector).any()

    def extended(self, vector) -> "Subspace":
        residual = self.reduce(vector)[0]
        column = int(np.flatnonzero(residual)[0])
        inverse = pow(int(residual[column]), self.q - 2, self.q)
        residual = (residual * inverse) % self.q
        rows = self.rows.copy()
        if rows.shape[0]:
            coefficient = rows[:, column].copy()
            nonzero = coefficient != 0
            if nonzero.any():
                rows[nonzero] = (rows[nonzero]
                                 - coefficient[nonzero, None] * residual[None, :]) % self.q
        other = Subspace(self.q, self.width)
        order = np.argsort(self.pivots + [column])
        other.rows = np.vstack([rows, residual.reshape(1, -1)])[order]
        other.pivots = sorted(self.pivots + [column])
        return other

    def extended_many(self, matrix) -> "Subspace":
        other = self
        for row in np.atleast_2d(np.asarray(matrix)):
            if not other.contains(row):
                other = other.extended(row)
        return other

    def elements(self) -> np.ndarray:
        if not self.pivots:
            return np.zeros((1, self.width), dtype=np.int64)
        combinations = np.array(list(product(range(self.q), repeat=self.rows.shape[0])),
                                dtype=np.int64)
        return (combinations @ self.rows) % self.q


def cover_cost(q: int, candidates: np.ndarray, targets: np.ndarray,
               limit: int) -> int | None:
    """Fewest of ``candidates`` whose span contains every row of ``targets``.

    Exhaustive depth-first search in increasing index order, so a returned value
    is a proved minimum and ``None`` proves that no ``t <= limit`` works.
    """

    width = targets.shape[1]
    start = Subspace(q, width)

    def uncovered(basis: Subspace) -> int:
        return basis.extended_many(targets).dimension - basis.dimension

    def search(basis: Subspace, first: int, budget: int) -> bool:
        need = uncovered(basis)
        if need == 0:
            return True
        if need > budget:
            return False
        if need == budget:
            # span(basis) + span(chosen) must equal span(basis) + span(targets),
            # so every chosen atom lies in that hull and greedy spanning is exact
            hull = basis.extended_many(targets)
            residual = hull.reduce(candidates[first:])
            inside = np.flatnonzero(~residual.any(axis=1)) + first
            current = basis
            for j in inside:
                if not current.contains(candidates[j]):
                    current = current.extended(candidates[j])
                    if current.dimension - basis.dimension == need:
                        return True
            return False
        residual = basis.reduce(candidates[first:])
        useful = np.flatnonzero(residual.any(axis=1)) + first
        for j in useful:
            if search(basis.extended(candidates[j]), int(j) + 1, budget - 1):
                return True
        return False

    for t in range(uncovered(start), limit + 1):
        if search(start, 0, t):
            return t
    return None


# ---------------------------------------------------------------------------
# N_k
# ---------------------------------------------------------------------------

def n_k_small(space: JetSpace, atoms_codes: np.ndarray, targets: np.ndarray,
              limit: int) -> int | None:
    """``N_k`` by plain exhaustive subset search.  Only for small atom sets."""

    atoms = space.decode(atoms_codes).astype(np.int64)
    atoms = atoms[atoms.any(axis=1)]
    return cover_cost(space.q, atoms, targets.astype(np.int64), limit)


def n_k_le_hull_plus_one(space: JetSpace, atoms_codes: np.ndarray,
                         targets: np.ndarray) -> int | None:
    """Decide ``N_k <= k + 1`` exhaustively, where ``k = targets.shape[0]``.

    If a solution with ``r`` atoms exists then ``U = span(atoms chosen)`` has
    ``dim U <= r`` and contains the hull ``H = span(targets)``, of dimension
    ``k``.  For ``r = k + 1`` therefore ``U = H`` or ``U = H + <a>`` for one
    atom ``a``, and every chosen atom lies in ``U``.  So it suffices to look, for
    each atom ``a``, at the atoms inside the ``(k+1)``-dimensional space
    ``H + <a>`` -- an exhaustive case distinction.
    """

    q = space.q
    k = targets.shape[0]
    hull = Subspace(q, space.dim).extended_many(targets.astype(np.int64))
    assert hull.dimension == k
    atom_set = atoms_codes

    def atoms_inside(sub: Subspace) -> np.ndarray:
        elements = sub.elements()
        codes = space.encode(elements)
        position = np.searchsorted(atom_set, codes)
        position = np.clip(position, 0, atom_set.shape[0] - 1)
        keep = atom_set[position] == codes
        rows = elements[keep]
        return rows[rows.any(axis=1)]

    best = cover_cost(q, atoms_inside(hull), targets.astype(np.int64), k + 1)
    if best == k:
        return best        # k is the absolute minimum, no need to look further

    # the distinct spaces H + <a> are indexed by atoms modulo H, normalised by
    # scaling the leading nonzero entry of the residual to 1
    direction_codes: list[np.ndarray] = []
    step = 1 << 17
    for start in range(0, atom_set.shape[0], step):
        residuals = hull.reduce(space.decode(atom_set[start:start + step]).astype(np.int64))
        residuals = residuals[residuals.any(axis=1)]
        if not residuals.shape[0]:
            continue
        pivot = (residuals != 0).argmax(axis=1)
        leading = residuals[np.arange(residuals.shape[0]), pivot]
        inverse = np.array([pow(int(v), q - 2, q) for v in range(q)], dtype=np.int64)
        residuals = (residuals * inverse[leading][:, None]) % q
        direction_codes.append(np.unique(space.encode(residuals)))
    for row in space.decode(np.unique(np.concatenate(direction_codes))).astype(np.int64):
        bigger = hull.extended(row)
        cost = cover_cost(q, atoms_inside(bigger), targets.astype(np.int64), k + 1)
        if cost is not None and (best is None or cost < best):
            best = cost
            if best == k:
                break
    return best
