#!/usr/bin/env python3
"""Decide ``N_2(g -> f) <= 3`` exactly, for atom sets too large for plain DFS.

Let ``F = span{1, f(x_1), f(x_2)}`` (dimension 3, because ``f`` is not constant)
and let ``T`` be a minimal solution with ``|T| = t``.  Put ``U = span(T) + F_3.1``.
Then ``F <= U`` and ``dim U <= t + 1``, and ``U`` is generated by ``1`` together
with the atoms of ``T``.  For ``t = 3`` this leaves only

    U = F        (all three atoms lie in the 27-element space F), or
    U = F + <a>  for a single atom ``a``  (dimension 4, 81 elements),

so the whole ``t <= 3`` question is decided by looking, for each atom ``a``, at
which atoms lie in the 81-element space ``F + <a>``.  Exhaustive.
"""

from __future__ import annotations

import json
import sys
import time
from itertools import product
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))

from affine_atoms import (  # noqa: E402
    P, Subspace, atom_tables, enumerate_classes, target_tables,
)

OUTPUT = Path(__file__).resolve().parent / "n2_le3.json"
QUADRATIC = ("linear", "rank1", "split", "anisotropic", "parabolic")


def space_elements(basis_rows: np.ndarray) -> np.ndarray:
    """All vectors of the row space of ``basis_rows``."""

    combinations = np.array(list(product(range(P), repeat=basis_rows.shape[0])),
                            dtype=np.int8)
    return (combinations @ basis_rows) % P


def cover_cost(candidates: np.ndarray, targets: np.ndarray, width: int,
               limit: int) -> int | None:
    """Fewest of ``candidates`` whose span with the constants covers ``targets``."""

    start = Subspace(width).extended(np.ones(width, dtype=np.int8))

    def uncovered(basis: Subspace) -> int:
        return basis.extended_many(targets).dimension - basis.dimension

    def search(basis: Subspace, first: int, budget: int) -> bool:
        need = uncovered(basis)
        if need == 0:
            return True
        if need > budget:
            return False
        residual = basis.reduce(candidates[first:])
        useful = np.flatnonzero(residual.any(axis=1)) + first
        for j in useful:
            if search(basis.extended(candidates[j]), int(j) + 1, budget - 1):
                return True
        return False

    for t in range(uncovered(start), limit + 1):
        if search(start, 0, t):
            return t
    return None


def n2_le3(atoms: np.ndarray, targets: np.ndarray) -> int | None:
    width = atoms.shape[1]
    atom_keys = {row.tobytes() for row in atoms}
    hull = Subspace(width).extended(np.ones(width, dtype=np.int8)).extended_many(targets)
    assert hull.dimension == 3

    best = None

    def consider(space: Subspace) -> None:
        nonlocal best
        elements = space_elements(space.rows)
        keep = np.array([row for row in elements if row.tobytes() in atom_keys],
                        dtype=np.int8)
        if keep.size == 0:
            return
        cost = cover_cost(keep.reshape(-1, width), targets, width, 3)
        if cost is not None and (best is None or cost < best):
            best = cost

    consider(hull)
    seen: set[bytes] = set()
    for atom in atoms:
        if hull.contains(atom):
            continue
        bigger = hull.extended(atom)
        key = bigger.rows.tobytes()
        if key in seen:
            continue
        seen.add(key)
        consider(bigger)
    return best


def main() -> None:
    classes = {c.key: c for c in enumerate_classes()}
    atoms = {key: atom_tables(classes[key].table, 2) for key in QUADRATIC}
    result: dict[str, dict[str, str]] = {}
    for g in QUADRATIC:
        row: dict[str, str] = {}
        for f in QUADRATIC:
            start = time.time()
            targets = target_tables(classes[f].table, 2)
            value = n2_le3(atoms[g], targets)
            row[f] = str(value) if value is not None else ">3"
            print(f"  N_2({g:<12}-> {f:<12}) {'=' if value else '>'} {row[f]:>3}"
                  f"   {time.time() - start:6.1f}s", flush=True)
        result[g] = row
    OUTPUT.write_text(json.dumps(result, indent=1))
    print()
    print("N_2(g -> f) decided up to 3:")
    print(f"{'':<14}" + "".join(f"{k:>14}" for k in QUADRATIC))
    for g in QUADRATIC:
        print(f"{g:<14}" + "".join(f"{result[g][f]:>14}" for f in QUADRATIC))


if __name__ == "__main__":
    main()
