#!/usr/bin/env python3
"""Exhaustive ``N_k(xy -> x^2+y^2) <= k+2`` over F_3, for k = 2 and k = 3.

The target is purely quadratic, so the linear parts of the atoms can be taken to
be zero (put ``s = t = 0``) and the problem is *exactly*

    N_k(xy -> x^2+y^2) = min { dim T : T <= Sym^2((F_3^{2k})^*) spanned by
                               products  l*m  of linear forms,
                               T contains  F_i = x_i^2 + y_i^2, i = 1..k } .

Deciding ``N_k <= k+2``.  A solution with ``r`` atoms spans a subspace ``T`` of
dimension at most ``r`` containing the hull ``H = span{F_1,...,F_k}`` of
dimension ``k``.  For ``r = k+2`` therefore ``T = H``, ``H + <p>`` or
``H + <p, p'>`` with ``p, p'`` products, and every chosen atom lies in ``T``.
So it suffices to run over

  * ``T_1 = H + <p>``  for one representative ``p`` per orbit of the stabiliser
    ``G`` of ``H`` inside ``GL_6(F_3)`` -- sound because ``G`` permutes the
    products and the valid ``T``'s, so if any valid ``T`` exists then some
    ``g.T`` contains an orbit representative;
  * ``T = T_1 + <p'>``, indexed by the residue of ``p'`` modulo ``T_1`` up to
    scalars, which is a cheap grouping of the product list.

``G`` is generated by the block permutations and the per-block similitudes of
``x^2 + y^2`` over ``F_3`` (order at least ``16^k k!``).
"""

from __future__ import annotations

import sys
import time
from itertools import product as iterproduct
from pathlib import Path

import numpy as np

P = 3


# ---------------------------------------------------------------------------
# Sym^2 coordinates
# ---------------------------------------------------------------------------

def pairs_of(n):
    return [(i, j) for i in range(n) for j in range(i, n)]


def matrix_to_vector(M, n, pairs):
    """Gram matrix (half off-diagonal) -> coefficient vector of the form."""

    out = np.zeros(len(pairs), dtype=np.int64)
    for t, (i, j) in enumerate(pairs):
        out[t] = M[i, i] if i == j else 2 * M[i, j]
    return out % P


def vector_to_matrix(v, n, pairs):
    M = np.zeros((n, n), dtype=np.int64)
    half = pow(2, P - 2, P)
    for t, (i, j) in enumerate(pairs):
        if i == j:
            M[i, i] = v[t]
        else:
            M[i, j] = M[j, i] = (v[t] * half) % P
    return M % P


def all_products(n, pairs):
    """Distinct nonzero coefficient vectors of ``l*m``, l, m linear forms."""

    vectors = np.array(list(iterproduct(range(P), repeat=n)), dtype=np.int64)
    ii = np.array([i for i, _ in pairs])
    jj = np.array([j for _, j in pairs])
    diagonal = ii == jj
    powers = (P ** np.arange(len(pairs))).astype(np.int64)
    codes = []
    for m in vectors:
        li, lj = vectors[:, ii], vectors[:, jj]
        mi, mj = m[ii][None, :], m[jj][None, :]
        quad = np.where(diagonal[None, :], li * mi, li * mj + lj * mi) % P
        codes.append(quad @ powers)
    codes = np.unique(np.concatenate(codes))
    return codes[codes != 0], powers


def decode(codes, powers, width):
    codes = np.atleast_1d(np.asarray(codes, dtype=np.int64))
    return ((codes[:, None] // powers[None, :]) % P).astype(np.int64)


# ---------------------------------------------------------------------------
# linear algebra
# ---------------------------------------------------------------------------

def rref(rows, width):
    rows = [np.array(r, dtype=np.int64) % P for r in rows]
    basis, pivots = [], []
    for row in rows:
        for b, c in zip(basis, pivots):
            if row[c]:
                row = (row - row[c] * b) % P
        nz = np.flatnonzero(row)
        if nz.size:
            c = int(nz[0])
            row = (row * pow(int(row[c]), P - 2, P)) % P
            basis = [(b - b[c] * row) % P if b[c] else b for b in basis]
            basis.append(row)
            pivots.append(c)
            order = np.argsort(pivots)
            basis = [basis[i] for i in order]
            pivots = [pivots[i] for i in order]
    return basis, pivots


def reduce_rows(matrix, basis, pivots):
    result = np.array(matrix, dtype=np.int64, copy=True) % P
    if result.ndim == 1:
        result = result.reshape(1, -1)
    for b, c in zip(basis, pivots):
        coefficient = result[:, c].copy()
        nonzero = coefficient != 0
        if nonzero.any():
            result[nonzero] = (result[nonzero]
                               - coefficient[nonzero, None] * b[None, :]) % P
    return result


def extend(basis, pivots, rows, width):
    """Adjoin ``rows`` to a reduced basis, returning a new reduced basis."""

    basis, pivots = list(basis), list(pivots)
    for row in np.atleast_2d(np.asarray(rows, dtype=np.int64)):
        row = row % P
        for b, c in zip(basis, pivots):
            if row[c]:
                row = (row - row[c] * b) % P
        nz = np.flatnonzero(row)
        if not nz.size:
            continue
        c = int(nz[0])
        row = (row * pow(int(row[c]), P - 2, P)) % P
        basis = [(b - b[c] * row) % P if b[c] else b for b in basis]
        basis.append(row)
        pivots.append(c)
        order = np.argsort(pivots)
        basis = [basis[i] for i in order]
        pivots = [pivots[i] for i in order]
    return basis, pivots


def contains_all(candidate_rows, targets, width):
    """Does span(candidate_rows) contain every row of targets?"""

    basis, pivots = rref(list(candidate_rows), width)
    return not reduce_rows(np.array(targets, dtype=np.int64), basis, pivots).any()


# ---------------------------------------------------------------------------
# the stabiliser of the target hull
# ---------------------------------------------------------------------------

def generators(k):
    """Block permutations and per-block similitudes of x^2+y^2 over F_3."""

    n = 2 * k
    gens = []
    # rotation of the anisotropic plane: (x,y) -> (x+y, x-y) scales x^2+y^2 by 2
    rot = np.array([[1, 1], [1, P - 1]], dtype=np.int64)
    # reflection
    ref = np.array([[0, 1], [1, 0]], dtype=np.int64)
    for block, small in ((0, rot), (0, ref)):
        M = np.eye(n, dtype=np.int64)
        M[2 * block:2 * block + 2, 2 * block:2 * block + 2] = small
        gens.append(M % P)
    if k >= 2:                      # transposition of blocks 0 and 1
        M = np.eye(n, dtype=np.int64)
        M[[0, 1, 2, 3]] = M[[2, 3, 0, 1]]
        gens.append(M % P)
    if k >= 3:                      # cycle of all blocks
        M = np.zeros((n, n), dtype=np.int64)
        for b in range(k):
            c = (b + 1) % k
            M[2 * b, 2 * c] = 1
            M[2 * b + 1, 2 * c + 1] = 1
        gens.append(M % P)
    return gens


def act(codes, A, powers, pairs, n):
    """Pull back every form in ``codes`` along ``x -> A x``."""

    vectors = decode(codes, powers, len(pairs))
    out = np.empty_like(codes)
    for index, v in enumerate(vectors):
        M = vector_to_matrix(v, n, pairs)
        out[index] = int((matrix_to_vector((A.T @ M @ A) % P, n, pairs) * powers).sum())
    return out


def orbit_representatives(codes, gens, powers, pairs, n):
    position = {int(c): i for i, c in enumerate(codes)}
    images = []
    for A in gens:
        moved = act(codes, A, powers, pairs, n)
        images.append(np.array([position[int(c)] for c in moved]))
    seen = np.zeros(codes.shape[0], dtype=bool)
    reps = []
    for start in range(codes.shape[0]):
        if seen[start]:
            continue
        reps.append(int(codes[start]))
        frontier = [start]
        seen[start] = True
        while frontier:
            new = []
            for i in frontier:
                for image in images:
                    j = int(image[i])
                    if not seen[j]:
                        seen[j] = True
                        new.append(j)
            frontier = new
    return reps


# ---------------------------------------------------------------------------
# the search
# ---------------------------------------------------------------------------

def decide(k: int) -> int | None:
    n = 2 * k
    pairs = pairs_of(n)
    width = len(pairs)
    start = time.time()
    codes, powers = all_products(n, pairs)
    print(f"  k={k}: {codes.shape[0]} distinct products in Sym^2(F_3^{n})"
          f"   {time.time()-start:5.1f}s", flush=True)

    targets = []
    for i in range(k):
        M = np.zeros((n, n), dtype=np.int64)
        M[2 * i, 2 * i] = 1
        M[2 * i + 1, 2 * i + 1] = 1
        targets.append(matrix_to_vector(M, n, pairs))
    targets = np.array(targets, dtype=np.int64)

    rows = decode(codes, powers, width)

    hull_basis, hull_pivots = rref(list(targets), width)
    assert len(hull_basis) == k

    # r = k : is H itself product-spanned?
    inside = rows[~reduce_rows(rows, hull_basis, hull_pivots).any(axis=1)]
    if inside.shape[0] and contains_all(inside, targets, width):
        return k

    start = time.time()
    reps = orbit_representatives(codes, generators(k), powers, pairs, n)
    print(f"  k={k}: {len(reps)} orbit representatives of products"
          f"   {time.time()-start:5.1f}s", flush=True)

    best = None
    start = time.time()
    for rep in reps:
        rep_row = decode(np.array([rep]), powers, width)[0]
        if not reduce_rows(rep_row, hull_basis, hull_pivots).any():
            continue                                   # rep lies in H
        basis1, pivots1 = rref(list(targets) + [rep_row], width)
        residues = reduce_rows(rows, basis1, pivots1)
        zero = ~residues.any(axis=1)

        # r = k+1
        inside = rows[zero]
        if inside.shape[0] and contains_all(inside, targets, width):
            return k + 1

        # r = k+2, grouped by the residue direction modulo T_1
        nonzero = np.flatnonzero(~zero)
        block = residues[nonzero]
        pivot = (block != 0).argmax(axis=1)
        leading = block[np.arange(block.shape[0]), pivot]
        inverse = np.array([0, 1, 2], dtype=np.int64)   # 1^-1 = 1, 2^-1 = 2
        normalised = (block * inverse[leading][:, None]) % P
        keys = (normalised * powers).sum(axis=1)
        order = np.argsort(keys, kind="stable")
        keys_sorted = keys[order]
        boundaries = np.flatnonzero(np.diff(keys_sorted)) + 1
        groups = np.split(order, boundaries)
        inside_basis, inside_pivots = rref(list(inside), width)
        for group in groups:
            if len(inside_basis) + len(group) < k:
                continue
            basis, pivots = extend(inside_basis, inside_pivots,
                                   rows[nonzero[group]], width)
            if len(basis) < k:
                continue
            if not reduce_rows(targets, basis, pivots).any():
                best = k + 2
                break
        if best is not None:
            break
    print(f"  k={k}: search finished in {time.time()-start:6.1f}s", flush=True)
    return best


def main() -> None:
    for k in (2, 3):
        value = decide(k)
        text = str(value) if value is not None else f">{k+2}"
        print(f"N_{k}(xy -> x^2+y^2) {'=' if value else '>'} {text}")
        print()


if __name__ == "__main__":
    main()
