"""G1 -- which tournaments are realised?  Mined from focused pools.

Key observation.  sigma = log(log r / log M) and psi = (1/2) log(log r * log M)
depend on the signature *only* through its number of fibers r and its largest
fiber M.  So inside a pool of signatures with the same (r, M) the exact part
d(psi) of the flow vanishes identically and

        A(a,b) = D(a,b)          exactly,

i.e. the tournament there is generated by the bounded defect alone.  This is
where cycles live: random pools spread psi over a range far larger than the
proved bound |D| < (log 2)/2, which is why they are almost always transitive.

The script enumerates such pools, computes A, and tallies which isomorphism
classes of tournament on n = 3,4,5,6 occur, certifying one witness of each
against 40-digit mpmath.

    python research/realizability/g1_mine.py [nmax] [pool_size]
"""
from __future__ import annotations

import csv
import itertools
import json
import math
import sys
import time
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
import common as C  # noqa: E402

HERE = Path(__file__).resolve().parent


# --------------------------------------------------------------------------
# isomorphism-class bookkeeping
# --------------------------------------------------------------------------

def perm_index(n):
    return np.array(list(itertools.permutations(range(n))), dtype=np.int64)


def canon_batch(M, perms):
    """Canonical (lex-least over relabelings) code of each tournament in M.

    M: (B, n, n) boolean upper-triangular-consistent adjacency.
    Returns (B,) int64 codes.
    """
    B, n, _ = M.shape
    iu = np.triu_indices(n, 1)
    weights = (1 << np.arange(len(iu[0])))[::-1].astype(np.int64)
    best = np.full(B, np.iinfo(np.int64).max, dtype=np.int64)
    for p in perms:
        Mp = M[:, p][:, :, p]
        bits = (Mp[:, iu[0], iu[1]] * weights).sum(axis=1)
        np.minimum(best, bits, out=best)
    return best


def all_classes(n):
    """{code: representative adjacency matrix} for all tournaments on n."""
    iu = np.triu_indices(n, 1)
    m = len(iu[0])
    perms = perm_index(n)
    Ms = np.zeros((1 << m, n, n), dtype=bool)
    bits = ((np.arange(1 << m)[:, None] >> np.arange(m)[None, :]) & 1).astype(bool)
    Ms[:, iu[0], iu[1]] = bits
    Ms[:, iu[1], iu[0]] = ~bits
    codes = canon_batch(Ms, perms)
    out = {}
    for k, c in enumerate(codes):
        if c not in out:
            out[int(c)] = Ms[k].copy()
    return out


# --------------------------------------------------------------------------
# focused pools
# --------------------------------------------------------------------------

def bucket(r, M, vmin=1, limit=None, seed=0):
    """All signatures with exactly r fibers, largest fiber exactly M."""
    rest = list(itertools.combinations_with_replacement(range(vmin, M + 1), r - 1))
    sigs = [tuple(sorted((M,) + t, reverse=True)) for t in rest]
    if limit and len(sigs) > limit:
        rng = np.random.default_rng(seed)
        idx = rng.choice(len(sigs), limit, replace=False)
        sigs = [sigs[i] for i in idx]
    return [C.Sig.of(s) for s in sigs]


def A_matrix(sigs, grid):
    tab = np.vstack([s.U(grid) for s in sigs])
    eR = np.array([math.log(s.R) for s in sigs])
    eL = np.array([math.log(s.Lam) for s in sigs])
    n = len(sigs)
    A = np.zeros((n, n))
    for i in range(n):
        diff = tab - tab[i]
        hi = np.maximum(diff.max(axis=1), np.maximum(eR - eR[i], eL - eL[i]))
        lo = np.minimum(diff.min(axis=1), np.minimum(eR - eR[i], eL - eL[i]))
        A[i] = 0.5 * (hi + lo)
    np.fill_diagonal(A, 0.0)
    return A


# --------------------------------------------------------------------------

def mine(A, n, classes, perms, tries, rng, tol=1e-6):
    """Sample n-subsets; return {code: subset} for the classes seen."""
    N = A.shape[0]
    found = {}
    S = A > 0
    block = 20000
    done = 0
    while done < tries and len(found) < len(classes):
        b = min(block, tries - done)
        idx = rng.integers(0, N, size=(b, n))
        ok = np.array([len(set(row)) == n for row in idx])
        idx = idx[ok]
        if len(idx) == 0:
            done += b
            continue
        sub = S[idx[:, :, None], idx[:, None, :]]
        amp = np.abs(A[idx[:, :, None], idx[:, None, :]])
        iu = np.triu_indices(n, 1)
        good = amp[:, iu[0], iu[1]].min(axis=1) > tol
        sub, idx = sub[good], idx[good]
        if len(sub):
            codes = canon_batch(sub, perms)
            for k, c in enumerate(codes):
                c = int(c)
                if c not in found:
                    found[c] = idx[k].tolist()
        done += b
    return found


def main():
    nmax = int(sys.argv[1]) if len(sys.argv) > 1 else 5
    limit = int(sys.argv[2]) if len(sys.argv) > 2 else 700
    grid = C.make_grid(-16.0, 16.0, 0.004)

    buckets = [(6, 12), (5, 12), (6, 20), (4, 12), (7, 12), (3, 12), (2, 40)]
    pools = {}
    for (r, M) in buckets:
        sigs = bucket(r, M, limit=limit, seed=r * 100 + M)
        if len(sigs) < 20:
            continue
        t0 = time.time()
        A = A_matrix(sigs, grid)
        pools[(r, M)] = (sigs, A)
        cyc = 0
        S = A > 0
        for i in range(len(sigs)):
            out = np.flatnonzero(S[i])
            inn = np.flatnonzero(S[:, i])
            if len(out) and len(inn):
                cyc += int(S[np.ix_(out, inn)].sum())
        print(f"pool r={r} M={M}: {len(sigs)} signatures, "
              f"{cyc//3} three-cycles of {math.comb(len(sigs),3)} triples "
              f"({time.time()-t0:.0f}s)")

    rows = []
    witnesses = {}
    rng = np.random.default_rng(7)
    for n in range(3, nmax + 1):
        classes = all_classes(n)
        perms = perm_index(n)
        seen = {}
        for key, (sigs, A) in pools.items():
            tries = 400000 if n <= 5 else 1200000
            got = mine(A, n, classes, perms, tries, rng)
            for c, idx in got.items():
                if c not in seen:
                    seen[c] = (key, idx)
        print(f"\nn={n}: {len(seen)}/{len(classes)} isomorphism classes realised")
        for c, (key, idx) in sorted(seen.items()):
            sigs, _ = pools[key]
            fam = [sigs[i] for i in idx]
            rows.append({"n": n, "code": c, "pool": f"r={key[0]},M={key[1]}",
                         "signatures": [tuple(int(v) for v in s.atoms) for s in fam]})
        missing = [c for c in classes if c not in seen]
        if missing:
            print(f"  missing codes: {missing}")
        # certify one witness per class at 40 digits
        worst = 0.0
        minmargin = math.inf
        for c, (key, idx) in sorted(seen.items()):
            sigs, _ = pools[key]
            fam = [sigs[i] for i in idx]
            Ac = np.zeros((n, n))
            err = 0.0
            for i in range(n):
                for j in range(i + 1, n):
                    _, _, A_mp, _, e = C.certified_A_d(fam[i], fam[j])
                    Ac[i, j], Ac[j, i] = A_mp, -A_mp
                    err = max(err, e)
            code2 = int(canon_batch((Ac > 0)[None, :, :], perms)[0])
            iu = np.triu_indices(n, 1)
            mm = float(np.min(np.abs(Ac[iu])))
            worst = max(worst, err)
            minmargin = min(minmargin, mm)
            witnesses[f"n{n}_code{c}"] = {
                "pool": f"r={key[0]},M={key[1]}",
                "signatures": [list(map(int, s.atoms)) for s in fam],
                "certified_min_|A|": mm,
                "class_confirmed": code2 == c,
            }
        print(f"  certified at 40 digits: max |double - mpmath| = {worst:.2e}, "
              f"smallest |A| over all witnesses = {minmargin:.3e}")

    with (HERE / "g1_classes.csv").open("w", newline="") as fh:
        wr = csv.writer(fh)
        wr.writerow(["n", "iso_code", "pool", "signatures"])
        for row in rows:
            wr.writerow([row["n"], row["code"], row["pool"],
                         " | ".join(str(s) for s in row["signatures"])])
    (HERE / "g1_witnesses.json").write_text(json.dumps(witnesses, indent=1))
    print(f"\nwrote {HERE/'g1_classes.csv'} and {HERE/'g1_witnesses.json'}")


if __name__ == "__main__":
    main()
